#!/bin/sh

cd ${0%/*} || exit 1

. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Decompose
runApplication decomposePar

# Run
runParallel $(getApplication);

# Recompose
runApplication reconstructPar

#VTK
runApplication foamToVTK
