#!/bin/sh

cd ${0%/*} || exit 1

. $WM_PROJECT_DIR/bin/tools/RunFunctions


# Potential Foam
#runApplication potentialFoam

# Decompose
#runApplication decomposePar

# Run
runParallel $(getApplication);

# Recompose
runApplication reconstructPar
